// Writes src/tokens.css from the TypeScript tables, so the stylesheet a consumer
// imports can never drift from the constants a consumer reads. Run `pnpm build:css`
// after changing a token.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { TOKENS_CSS } from "../src/index.js";

const out = resolve(dirname(fileURLToPath(import.meta.url)), "../src/tokens.css");
writeFileSync(out, `/* GENERATED by scripts/emit-css.ts — edit src/index.ts, not this file. */\n${TOKENS_CSS}`, "utf8");
console.log(`wrote ${out} (${TOKENS_CSS.length} bytes)`);
